kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-read-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "watch", "list"]
