apiVersion : apps/v1
kind: Deployment
metadata:
  name: "poi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi 
    spec:
      containers:
        - name: "poi"
          image: "registryrzr0385.azurecr.io/tripinsights/poi:1.0"
          ports:
          - containerPort: 80
          env:
           - name: SQL_USER
             value: $sqluser
           - name: SQL_PASSWORD
             value: $sqlpassword
           - name: SQL_SERVER
             value: $sqlserver
           - name: SQL_DBNAME
             value: $sqldbname
---
apiVersion: v1
kind: Service
metadata:
    name: "poi"
    labels:
        app: "poi"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "poi"

