apiVersion: v1
kind: Secret
metadata:
  name: sql-user
data:
  sqluser: c3FsYWRtaW5yWnIwMzg1
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-password
data:
  sqlpassword: UEBzc3cwcmQxMjMk 
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-server
data:
  sqlserver:  c3Fsc2VydmVycnpyMDM4NS5kYXRhYmFzZS53aW5kb3dzLm5ldA==
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-dbname
data:
  sqldbname: bXlkcml2aW5nREI=
---

apiVersion : apps/v1
kind: Deployment
metadata:
  name: "poi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi 
    spec:
      containers:
        - name: "poi"
          image: "registryrzr0385.azurecr.io/tripinsights/poi:1.0"
          ports:
          - containerPort: 80
          env:
           - name: SQL_USER
             value: "sqladminrZr0385"
           - name: SQL_PASSWORD
             value: "P@ssw0rd123$"
           - name: SQL_SERVER
             value: "sqlserverrzr0385.database.windows.net"
           - name: SQL_DBNAME
             value: "mydrivingDB"
        
---
apiVersion: v1
kind: Service
metadata:
    name: "poi"
    labels:
        app: "poi"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "poi"

