apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tripviewer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer 
    spec:
      containers:
        - name: "tripviewer"
          image: "registryrzr0385.azurecr.io/tripinsights/tripviewer:1.0"  
          ports:
          - containerPort: 80
          env:
           - name: SQL_USER
             value: "sqladminrZr0385"
           - name: SQL_PASSWORD
             value: "P@ssw0rd123$"
           - name: SQL_SERVER
             value: "sqlserverrzr0385.database.windows.net"
           - name: SQL_DBNAME
             value: "mydrivingDB"
           - name: "USERPROFILE_API_ENDPOINT"
             value: "http://10.0.184.56"
           - name: "TRIPS_API_ENDPOINT"
             value: http://52.139.188.248:8080"
---
apiVersion: v1
kind: Service
metadata:
    name: "tripviewer"
    labels:
        app: "tripviewer"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tripviewer"
