apiVersion : apps/v1
kind: Deployment
metadata:
  name: "user-java"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java 
    spec:
      containers:
        - name: "user-java"
          image: "registryrzr0385.azurecr.io/tripinsights/user-java:1.0"  
          ports:
          - containerPort: 80
          env:
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: sqldbname
                  key: sqldbname
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlpassword
                  key: sqlpassword
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: sqlserver
                  key: sqlserver
            - name: SQL_USER
              valueFrom: 
                secretKeyRef:
                  name: sqluser
                  key: sqluser
---
apiVersion: v1
kind: Service
metadata:
    name: "user-java"
    labels:
        app: "user-java"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "user-java"
