apiVersion : apps/v1
kind: Deployment
metadata:
  name: "userprofile"
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: "userprofile"
          image: "registryrzr0385.azurecr.io/tripinsights/userprofile:1.0"
          ports:
          - containerPort: 80
          env:
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: sqldbname
                  key: sqldbname
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlpassword
                  key: sqlpassword
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: sqlserver
                  key: sqlserver
            - name: SQL_USER
              valueFrom: 
                secretKeyRef:
                  name: sqluser
                  key: sqluser
---
apiVersion: v1
kind: Service
metadata:
    name: "userprofile"
    labels:
        app: "userprofile"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "userprofile"
