apiVersion : apps/v1
kind: Deployment
metadata:
  name: "user-java"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java 
    spec:
      containers:
        - name: "user-java"
          image: "registryrzr0385.azurecr.io/tripinsights/user-java:1.0"  
          ports:
          - containerPort: 80
          env:
           - name: SQL_USER
             value: "sqladminrZr0385"
           - name: SQL_PASSWORD
             value: "P@ssw0rd123$"
           - name: SQL_SERVER
             value: "sqlserverrzr0385.database.windows.net"
           - name: SQL_DBNAME
             value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
    name: "user-java"
    labels:
        app: "user-java"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "user-java"
