kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdev-read-role
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-read-access
subjects:
- kind: Group
  namespace: api
  name: "938e822e-25a7-4a2f-9011-27216baba312"
