kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webdev-read-role
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-read-access
subjects:
- kind: Group
  namespace: web
  name: c92bf3e1-6fdf-4687-93fd-29d2d45a1d7f
