kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webdev-write-role
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-write-access
subjects:
- kind: Group
  namespace: web
  name: "938e822e-25a7-4a2f-9011-27216baba312"
