kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend-poi
  namespace: api
spec:
  podSelector:
    matchLabels:
      app:  poi
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: api
      podSelector:
        matchLabels:
          app: userprofile
      podSelector:
        matchLabels:
          app: poi
      podSelector:
        matchLabels:
          app: user-java
      podSelector:
        matchLabels:
          app: trips
    - namespaceSelector:
        matchLabels:
          app: web
      podSelector:
        matchLabels:
          app: tripviewer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend-userprofile
  namespace: api
spec:
  podSelector:
    matchLabels:
      app:  userprofile
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: api
      podSelector:
        matchLabels:
          app: userprofile
      podSelector:
        matchLabels:
          app: poi
      podSelector:
        matchLabels:
          app: user-java
      podSelector:
        matchLabels:
          app: trips
    - namespaceSelector:
        matchLabels:
          app: web
      podSelector:
        matchLabels:
          app: tripviewer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend-user-java
  namespace: api
spec:
  podSelector:
    matchLabels:
      app:  poi
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: api
      podSelector:
        matchLabels:
          app: userprofile
      podSelector:
        matchLabels:
          app: poi
      podSelector:
        matchLabels:
          app: user-java
      podSelector:
        matchLabels:
          app: trips
    - namespaceSelector:
        matchLabels:
          app: web
      podSelector:
        matchLabels:
          app: tripviewer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend-trips
  namespace: api
spec:
  podSelector:
    matchLabels:
      app:  trips
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: api
      podSelector:
        matchLabels:
          app: userprofile
      podSelector:
        matchLabels:
          app: poi
      podSelector:
        matchLabels:
          app: user-java
      podSelector:
        matchLabels:
          app: trips
    - namespaceSelector:
        matchLabels:
          app: web
      podSelector:
        matchLabels:
          app: tripviewer



