kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend-policy
  namespace: api
spec:
  podSelector:
    matchLabels:
      app:
        - poi
        - userprofile
        - user-java
        - trips
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: api
      podSelector:
        matchLabels:
          app:
            - userprofile
            - poi
            - user-java
            - trips
    - namespaceSelector:
        matchLabels:
          app: web
      podSelector:
        matchLabels:
          app:
            - tripviewer

