name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
#  sqluser: 'c3FsYWRtaW4='
#  sqlpassword: 'UEBzc3cwcmQxMjMk'
#  sqlserver: 'c3Fsc2VydmVycnpyMDM4NS5kYXRhYmFzZS53aW5kb3dzLm5ldA=='
#  sqldbname: 'bXlkcml2aW5nREI='
on:
  [ push ]
#    paths: 
#        [ .github/workflows/aks-deployment.yml ]
jobs:  
  
  aks-deploy:
    
    runs-on: ubuntu-latest

    # Deployment to Kubernetes
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AKS_CREDENTIALS }}' # Azure credentials
        resource-group: 'teamResources-hackTeam1'
        cluster-name: 'aks-ch3'
      id: login
      
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep tripviewer | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace tripviewer`
        fi
   
    - uses: azure/k8s-deploy@v1
      with:
        namespace: tripviewer 
        manifests: |
          poi.yml
          userprofile.yml
          user-java.yml
          trips.yml
          tripviewer.yml
        images: |
          registryrzr0385.azurecr.io/tripinsights/poi:1.0
          registryrzr0385.azurecr.io/tripinsights/userpforile:1.0
          registryrzr0385.azurecr.io/tripinsights/user-java:1.0
          registryrzr0385.azurecr.io/tripinsights/trips:1.0
          registryrzr0385.azurecr.io/tripinsights/tripviewer:1.0
        imagepullsecrets: |
          hack1reposecret
