name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  [ push ]
#    paths: 
#        [ .github/workflows/aks-deployment.yml ]
jobs:  
  
  aks-deploy:
    
    runs-on: ubuntu-latest
    
    # Deployment to Kubernetes
    
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: 'teamResources-hackTeam1'
        cluster-name: 'aks-tripviewer'
      id: login
    

    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep tripviewer | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace tripviewer`
        fi
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: registryrzr0385.azurecr.io
        container-registry-username: ${{ secrets.acr_username }}
        container-registry-password: ${{ secrets.acr_password }}
        secret-name: hack1reposecret   
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'tripviewer'
        secret-type: 'generic'
        arguments:  --from-literal=SQL_USER=${{ secrets.SQL_USER }}   
        secret-name: SQL_USER   
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'tripviewer'
        secret-type: 'generic'
        arguments:   --from-literal=SQL_PASSWORD=${{ secrets.SQL_PASSWORD }} 
        secret-name: SQL_PASSWORD
   
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'tripviewer'
        secret-type: 'generic'
        arguments:  --from-literal=SQL_SERVER=${{ secrets.SQL_SERVER }} 
        secret-name: SQL_SERVER 
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'tripviewer'
        secret-type: 'generic'
        arguments:  --from-literal=SQL_DBNAME=${{ secrets.SQL_DBNAME }} 
        secret-name: SQL_DBNAME 
    - uses: azure/k8s-deploy@v1
      with:
        namespace: tripviewer 
        manifests: |
          poi.yml

        images: |
          registryrzr0385.azurecr.io/tripinsights/poi:1.0
        imagepullsecrets: |
          hack1reposecret
