on:
  push:
    paths: 
      [ .github/workflows/secrets.yml ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      sqlserver: 'SQL_SERVER'
      sqluser: 'SQL_USER'
      sqlpassword: 'SQL_PASSWORD'
      sqldbname: 'SQL_DBNAME'
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name: kv-access
      uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: hac1-kv
        secrets: sqlserver,sqluser,sqlpassword,sqldbname 
      id: myGetSecretAction
      
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AKS_CREDENTIALS }}' # Azure credentials
        resource-group: 'teamResources-hackTeam1'
        cluster-name: 'aks-ch3'   
      id: login
    
    - name: Create secrets on AKS cluster
      run: |
        kubectl create secret $sqlserver --value ${{ steps.myGetSecretAction.outputs.sqlserver }} --namespace=api
        kubectl create secret $sqluser --value ${{ steps.myGetSecretAction.outputs.sqluser }} --namespace=api
        kubectl create secret $sqlpassword --value ${{ steps.myGetSecretAction.outputs.sqlpassword }} --namespace=api
        kubectl create secret $sqldbname --value ${{ steps.myGetSecretAction.outputs.sqldbname }} --namespace=api
