on:
  push:
    paths: 
      [ .github/workflows/secrets.yml ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      sqlserver: 'SQL_SERVER'
      sqluser: 'SQL_USER'
      sqlpassword: 'SQL_PASSWORD'
      sqldbname: 'SQL_DBNAME'
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name: kv-access
      uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: hac1-kv
        secrets: sqlserver,sqluser,sqlpassword,sqldbname 
      id: myGetSecretAction
      
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AKS_CREDENTIALS }}' # Azure credentials
        resource-group: 'teamResources-hackTeam1'
        cluster-name: 'aks-ch3'   
      id: login
    
    - name: Create secret sqlserver
      run: |
        secretpresent=`kubectl get secret sqlserver --namespace=api | grep web | wc -l`
        if [ $secretpresent -ne 0 ]
        then
           kubectl delete secret sqlserver --namespace=api
        fi
        kubectl create secret generic sqlserver --from-literal=$sqlserver=${{ steps.myGetSecretAction.outputs.sqlserver }} --namespace=api
    
    - name: Create secret sqluser
      run: |
        secretpresent=`kubectl get secret sqluser --namespace=api | grep web | wc -l`
        if [ $secretpresent -ne 0 ]
        then
          kubectl delete secret sqluser --namespace=api
        fi
        kubectl create secret generic sqluser --from-literal=$sqluser=${{ steps.myGetSecretAction.outputs.sqluser }} --namespace=api
          
    - name: Create secret sqlpassword
      run: |
        secretpresent=`kubectl get secret sqlpassword --namespace=api | grep web | wc -l`
        if [ $secretpresent -ne 0 ]
        then
          kubectl delete secret sqlpassword --namespace=api
        fi
        kubectl create secret generic sqlpassword --from-literal=$sqlpassword=${{ steps.myGetSecretAction.outputs.sqlpassword }} --namespace=api
        
    - name: Create secret sqldbname
      run: |
        secretpresent=`kubectl get secret sqldbname --namespace=api | grep web | wc -l`
        if [ $secretpresent -ne 0 ]
        then
          kubectl delete secret sqldbname --namespace=api
        fi
        kubectl create secret generic sqldbname --from-literal=$sqldbname=${{ steps.myGetSecretAction.outputs.sqldbname }} --namespace=api
  
