on:
  push:
    paths: 
      [ .github/workflows/secrets.yml ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      sqlserver: none
      sqluser: none
      sqldbname: none
      sqlpassword: none
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: get KV secrets
      uses: azure/CLI@v1
      with:
        inlineScript: | 
            sqlserverfromkv=$(az keyvault secret show --name "sqlservertest" --vault-name "hac1-kv" --query value -o tsv)
            sqluserfromkv=$(az keyvault secret show --name "sqlusertest" --vault-name "hac1-kv" --query value -o tsv)
            sqlpasswordfromkv=$(az keyvault secret show --name "sqlpasswordtest" --vault-name "hac1-kv" --query value -o tsv)
            sqldbnamefromkv=$(az keyvault secret show --name "sqldbnametest" --vault-name "hac1-kv" --query value -o tsv)
            echo "::set-env name=sqlserver::$sqlserverfromkv"
            echo "::set-env name=sqluser::$sqluserfromkv"
            echo "::set-env name=sqlpassword::$sqlpasswordfromkv"
            echo "::set-env name=sqldbname::$sqldbnamefromkv"
      
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AKS_CREDENTIALS }}' # Azure credentials
        resource-group: 'teamResources-hackTeam1'
        cluster-name: 'aks-ch3'   
      id: login
     
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=sqlserver=${{ env.sqlserver }}
        secret-name: sqlserver
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=sqluser=${{ env.sqluser }} 
        secret-name: sqluser

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=sqlpassword=${{ env.sqlpassword }} 
        secret-name: sqlpassword
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=sqldbname=${{ env.sqldbname }}  
        secret-name: sqldbname
    
