on:
  push:
    paths: 
      [ .github/workflows/secrets.yml ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name: kv-access
      uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: hac1-kv
        secrets: sqlserver,sqluser,sqlpassword,sqldbname 
      id: myGetSecretAction
   
    - run: echo ${{ steps.myGetSecretAction.outputs.sqlserver }}
      
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AKS_CREDENTIALS }}' # Azure credentials
        resource-group: 'teamResources-hackTeam1'
        cluster-name: 'aks-ch3'   
      id: login
      
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=sqlserver=${{ steps.myGetSecretAction.outputs.sqlserver }} 
        secret-name: sqlserver
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  ---from-literal=sqluser=${{ steps.myGetSecretAction.outputs.sqluser }} 
        secret-name: sqluser
        
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=sqlserver=${{ steps.myGetSecretAction.outputs.sqlpassword }} 
        secret-name: sqlpassword
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=sqlserver=${{ steps.myGetSecretAction.outputs.sqlname }} 
        secret-name: sqldbname
      
