on:
  push:
    paths: 
      [ .github/workflows/secrets.yml ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      sqlserver: "SQL_SERVER"
      sqluser: 'SQL_USER'
      sqlpassword: 'SQL_PASSWORD'
      sqldbname: 'SQL_DBNAME'
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name: kv-access
      uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: hac1-kv
        secrets: sqlserver,sqluser,sqlpassword,sqldbname 
      id: myGetSecretAction
      
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AKS_CREDENTIALS }}' # Azure credentials
        resource-group: 'teamResources-hackTeam1'
        cluster-name: 'aks-ch3'   
      id: login
     
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=${{ env.sqlserver }}=${{ steps.myGetSecretAction.outputs.sqlserver }} 
        secret-name: sqlserver
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=${{ env.sqluser }}=${{ steps.myGetSecretAction.outputs.sqluser }} 
        secret-name: sqluser

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=${{ env.sqlpasswoword }}=${{ steps.myGetSecretAction.outputs.sqlpassword }} 
        secret-name: sqlpassword
    - uses: azure/k8s-create-secret@v1
      with:
        namespace: 'api'
        secret-type: 'generic'
        arguments:  --from-literal=${{ env.sqldbname }}=${{ steps.myGetSecretAction.outputs.sqldbname }} 
        secret-name: sqldbname
    
